/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package voting.system;

/**
 *
 * @author nerfe
 */
public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddCandidate = new javax.swing.JButton();
        btnRemoveCandidate = new javax.swing.JButton();
        btnViewCandidates = new javax.swing.JButton();
        btnViewResults = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("pnlAdminDashboard"); // NOI18N

        jLabel1.setText("Admin Dashboard");

        btnAddCandidate.setText("Add Candidate");
        btnAddCandidate.addActionListener(this::btnAddCandidateActionPerformed);

        btnRemoveCandidate.setText("Remove Candidate");
        btnRemoveCandidate.addActionListener(this::btnRemoveCandidateActionPerformed);

        btnViewCandidates.setText("View Candidates");
        btnViewCandidates.addActionListener(this::btnViewCandidatesActionPerformed);

        btnViewResults.setText("View Results");
        btnViewResults.addActionListener(this::btnViewResultsActionPerformed);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRemoveCandidate)
                            .addComponent(btnAddCandidate)
                            .addComponent(btnViewCandidates)
                            .addComponent(btnViewResults)
                            .addComponent(btnLogout))))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(btnAddCandidate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRemoveCandidate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewCandidates)
                .addGap(18, 18, 18)
                .addComponent(btnViewResults)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCandidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCandidateActionPerformed
        // TODO add your handling code here:
        new MannageCandidates().setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnAddCandidateActionPerformed

    private void btnRemoveCandidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveCandidateActionPerformed
        // TODO add your handling code here:
        new MannageCandidates().setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnRemoveCandidateActionPerformed

    private void btnViewCandidatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCandidatesActionPerformed
        // TODO add your handling code here:
        new MannageCandidates().setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnViewCandidatesActionPerformed

    private void btnViewResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewResultsActionPerformed
        // TODO add your handling code here:
        new ResultsPage().setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnViewResultsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        Session.logout();

        new LoginPage().setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCandidate;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRemoveCandidate;
    private javax.swing.JButton btnViewCandidates;
    private javax.swing.JButton btnViewResults;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
