/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package voting.system;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;

/**
 *
 * @author nerfe
 */
public class MannageCandidates extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MannageCandidates.class.getName());

    /**
     * Creates new form MannageCandidates
     */
    public MannageCandidates() {
        initComponents();
        loadCandidates();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCandidateName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbPosition = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        scrollCandidates = new javax.swing.JScrollPane();
        tblCandidates = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("pnlManageCandidates"); // NOI18N

        jLabel1.setText("Mannage Candidates");

        jLabel2.setText("Name:");

        jLabel3.setText("Position:");

        cmbPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "President", "Vice President", "Secretary", "Treasurer", "Auditor" }));

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        tblCandidates.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Position", "Votes"
            }
        ));
        tblCandidates.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCandidatesMouseClicked(evt);
            }
        });
        scrollCandidates.setViewportView(tblCandidates);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCandidateName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)
                        .addGap(29, 29, 29)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(scrollCandidates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(219, 219, 219))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCandidateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addGap(34, 34, 34)
                .addComponent(scrollCandidates, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow =
            tblCandidates.getSelectedRow();

        if (selectedRow == -1) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please select a candidate."
            );

            return;
        }

        int candidateId =
                Integer.parseInt(
                        tblCandidates
                                .getValueAt(selectedRow, 0)
                                .toString()
                );

        int confirm =
                javax.swing.JOptionPane.showConfirmDialog(
                        this,
                        "Delete this candidate?",
                        "Confirm Delete",
                        javax.swing.JOptionPane.YES_NO_OPTION
                );

        if (confirm != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        DataManager.deleteCandidate(candidateId);

        loadCandidates();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCandidates.getSelectedRow();

        // No candidate selected
        if (selectedRow == -1) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please select a candidate to edit.",
                    "Edit Candidate",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        // Get values from the input fields
        String name = txtCandidateName.getText().trim();

        String position =
                cmbPosition.getSelectedItem().toString();

        // Validate name
        if (name.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please enter the candidate name.",
                    "Edit Candidate",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        // Get candidate ID from selected table row
        int candidateId =
                Integer.parseInt(
                        tblCandidates
                                .getValueAt(selectedRow, 0)
                                .toString()
                );

        // Confirm editing
        int confirm =
                javax.swing.JOptionPane.showConfirmDialog(
                        this,
                        "Update this candidate?",
                        "Confirm Edit",
                        javax.swing.JOptionPane.YES_NO_OPTION
                );

        if (confirm != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        // Update candidate
        boolean success =
                DataManager.updateCandidate(
                        candidateId,
                        name,
                        position
                );

        if (success) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Candidate updated successfully.",
                    "Edit Candidate",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

            // Refresh table
            loadCandidates();

            // Clear input fields
            clearFields();

        } else {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Failed to update candidate.",
                    "Edit Candidate",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String name =
            txtCandidateName.getText().trim();

        String position =
                cmbPosition.getSelectedItem().toString();

        if (name.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please enter candidate name.",
                    "Candidate",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        boolean success =
                DataManager.addCandidate(
                        name,
                        position
                );

        if (success) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Candidate added successfully."
            );

            txtCandidateName.setText("");

            loadCandidates();

        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void tblCandidatesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCandidatesMouseClicked
        // TODO add your handling code here:
        int row = tblCandidates.getSelectedRow();

        if (row == -1) {
            return;
        }

        txtCandidateName.setText(
                tblCandidates
                        .getValueAt(row, 1)
                        .toString()
        );

        cmbPosition.setSelectedItem(
                tblCandidates
                        .getValueAt(row, 2)
                        .toString()
        );
    }//GEN-LAST:event_tblCandidatesMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new AdminDashboard().setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void loadCandidates() {

    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel)
                    tblCandidates.getModel();

        model.setRowCount(0);

        for (Candidate candidate :
                DataManager.getCandidates()) {

            model.addRow(new Object[]{
                candidate.getId(),
                candidate.getName(),
                candidate.getPosition(),
                candidate.getVotes()
            });
        }
    }
    
    
    private void clearFields() {

        txtCandidateName.setText("");

        if (cmbPosition.getItemCount() > 0) {
            cmbPosition.setSelectedIndex(0);
        }

        tblCandidates.clearSelection();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MannageCandidates().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JComboBox<String> cmbPosition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane scrollCandidates;
    private javax.swing.JTable tblCandidates;
    private javax.swing.JTextField txtCandidateName;
    // End of variables declaration//GEN-END:variables
}
