/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package voting.system;

/**
 *
 * @author nerfe
 */
public class VotingPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VotingPage.class.getName());

    /**
     * Creates new form VotingPage
     */
    public VotingPage() {
        initComponents();
        loadCandidates();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollCandidates = new javax.swing.JScrollPane();
        tblCandidates = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnCastVote = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("pnlVoting"); // NOI18N

        tblCandidates.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Candidate", "Position", "Vote", "Select"
            }
        ));
        scrollCandidates.setViewportView(tblCandidates);

        jLabel1.setText("CANDIDATES");

        btnCastVote.setText("CAST VOTE");
        btnCastVote.addActionListener(this::btnCastVoteActionPerformed);

        jLabel2.setText("Select Candidate");

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(scrollCandidates, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addComponent(btnCastVote))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollCandidates, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCastVote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCastVoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCastVoteActionPerformed
        // TODO add your handling code here:
        int selectedRow =
            tblCandidates.getSelectedRow();

        if (selectedRow == -1) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please select a candidate.",
                    "Voting",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        int candidateId =
                Integer.parseInt(
                        tblCandidates
                                .getValueAt(selectedRow, 0)
                                .toString()
                );

        String candidateName =
                tblCandidates
                        .getValueAt(selectedRow, 1)
                        .toString();

        String position =
                tblCandidates
                        .getValueAt(selectedRow, 2)
                        .toString();

        new VoteConfirmation(
                candidateId,
                candidateName,
                position
        ).setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnCastVoteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    
    private void loadCandidates() {

        javax.swing.table.DefaultTableModel model =
                (javax.swing.table.DefaultTableModel)
                        tblCandidates.getModel();

        model.setRowCount(0);

        for (Candidate candidate :
                DataManager.getCandidates()) {

            model.addRow(new Object[]{
                candidate.getId(),
                candidate.getName(),
                candidate.getPosition(),
                candidate.getVotes()
            });
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VotingPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCastVote;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane scrollCandidates;
    private javax.swing.JTable tblCandidates;
    // End of variables declaration//GEN-END:variables
}
